# Uncomment the next line to define a global platform for your project
platform :ios, '16.0' # Or your minimum iOS deployment target, e.g., '15.0' for newer projects

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  # The line below integrates your Kotlin Multiplatform shared module.
  # Replace 'shared' with the actual name of your shared module if different.
  # The name 'ComposeApp' typically comes from baseName in build.gradle.kts
  pod 'ComposeApp', :path => '../composeApp'

  # If you have other iOS-specific pods, add them here
  # pod 'Firebase/Analytics'

end